// AUTO-GENERATED by python/tools/gen_smpl_rest_header.py — do not edit by hand.
// Source: smpl_rest.json (SMPL neutral model, β=0 rest pose, Y-up meters).

#pragma once

#include "CoreMinimal.h"

namespace SMPLRest
{
    /** Number of SMPL body joints. */
    constexpr int32 NumJoints = 24;

    /** Parent joint index (-1 = root/pelvis). */
    constexpr int32 Parents[NumJoints] = {
        -1,  //  0 pelvis
        0,  //  1 L_hip
        0,  //  2 R_hip
        0,  //  3 spine1
        1,  //  4 L_knee
        2,  //  5 R_knee
        3,  //  6 spine2
        4,  //  7 L_ankle
        5,  //  8 R_ankle
        6,  //  9 spine3
        7,  // 10 L_foot
        8,  // 11 R_foot
        9,  // 12 neck
        9,  // 13 L_collar
        9,  // 14 R_collar
        12,  // 15 head
        13,  // 16 L_shoulder
        14,  // 17 R_shoulder
        16,  // 18 L_elbow
        17,  // 19 R_elbow
        18,  // 20 L_wrist
        19,  // 21 R_wrist
        20,  // 22 L_hand
        21,  // 23 R_hand
    };

    /**
     * Primary chain child for each joint (used for bone direction). -1 = leaf.
     * Pelvis picks spine1 as primary (torso), not the hips (they're separate
     * chains). Wrist picks hand even though hand has no UE counterpart —
     * gives wrist a bone direction for swing retargeting.
     */
    constexpr int32 ChainChild[NumJoints] = {
        3,   // 0  pelvis → spine1  (primary spine child)
        4,   // 1  L_hip → L_knee
        5,   // 2  R_hip → R_knee
        6,   // 3  spine1 → spine2
        7,   // 4  L_knee → L_ankle
        8,   // 5  R_knee → R_ankle
        9,   // 6  spine2 → spine3
        10,  // 7  L_ankle → L_foot
        11,  // 8  R_ankle → R_foot
        12,  // 9  spine3 → neck  (primary; L_collar/R_collar are separate chains)
        -1,  // 10 L_foot  (leaf)
        -1,  // 11 R_foot  (leaf)
        15,  // 12 neck → head
        16,  // 13 L_collar → L_shoulder
        17,  // 14 R_collar → R_shoulder
        -1,  // 15 head  (leaf)
        18,  // 16 L_shoulder → L_elbow
        19,  // 17 R_shoulder → R_elbow
        20,  // 18 L_elbow → L_wrist
        21,  // 19 R_elbow → R_wrist
        22,  // 20 L_wrist → L_hand
        23,  // 21 R_wrist → R_hand
        -1,  // 22 L_hand  (leaf, no UE counterpart)
        -1,  // 23 R_hand  (leaf, no UE counterpart)
    };

    /** SMPL joint names (for logging / debugging). */
    static const TCHAR* const JointNames[NumJoints] = {
        TEXT("pelvis"),  //  0
        TEXT("L_hip"),  //  1
        TEXT("R_hip"),  //  2
        TEXT("spine1"),  //  3
        TEXT("L_knee"),  //  4
        TEXT("R_knee"),  //  5
        TEXT("spine2"),  //  6
        TEXT("L_ankle"),  //  7
        TEXT("R_ankle"),  //  8
        TEXT("spine3"),  //  9
        TEXT("L_foot"),  // 10
        TEXT("R_foot"),  // 11
        TEXT("neck"),  // 12
        TEXT("L_collar"),  // 13
        TEXT("R_collar"),  // 14
        TEXT("head"),  // 15
        TEXT("L_shoulder"),  // 16
        TEXT("R_shoulder"),  // 17
        TEXT("L_elbow"),  // 18
        TEXT("R_elbow"),  // 19
        TEXT("L_wrist"),  // 20
        TEXT("R_wrist"),  // 21
        TEXT("L_hand"),  // 22
        TEXT("R_hand"),  // 23
    };

    /** UE mannequin bone name for each SMPL joint (empty = skip). */
    static const TCHAR* const UEBoneNames[NumJoints] = {
        TEXT("pelvis"),  //  0 pelvis
        TEXT("thigh_l"),  //  1 L_hip
        TEXT("thigh_r"),  //  2 R_hip
        TEXT("spine_01"),  //  3 spine1
        TEXT("calf_l"),  //  4 L_knee
        TEXT("calf_r"),  //  5 R_knee
        TEXT("spine_02"),  //  6 spine2
        TEXT("foot_l"),  //  7 L_ankle
        TEXT("foot_r"),  //  8 R_ankle
        TEXT("spine_03"),  //  9 spine3
        TEXT("ball_l"),  // 10 L_foot
        TEXT("ball_r"),  // 11 R_foot
        TEXT("neck_01"),  // 12 neck
        TEXT("clavicle_l"),  // 13 L_collar
        TEXT("clavicle_r"),  // 14 R_collar
        TEXT("head"),  // 15 head
        TEXT("upperarm_l"),  // 16 L_shoulder
        TEXT("upperarm_r"),  // 17 R_shoulder
        TEXT("lowerarm_l"),  // 18 L_elbow
        TEXT("lowerarm_r"),  // 19 R_elbow
        TEXT("hand_l"),  // 20 L_wrist
        TEXT("hand_r"),  // 21 R_wrist
        TEXT(""),  // 22 L_hand
        TEXT(""),  // 23 R_hand
    };

    /**
     * SMPL joint world positions at rest (β=0, pose=0). SMPL Y-up meters.
     * pelvis is at approximately (0, -0.22, 0.03) — SMPL canonical has the
     * root offset from the origin by the mesh centroid; we keep that offset
     * for accurate FK.
     */
    constexpr float RestPositionsYupMeters[NumJoints][3] = {
        { -0.001795f, -0.223333f, +0.028219f },  //  0 pelvis
        { +0.067725f, -0.314740f, +0.021404f },  //  1 L_hip
        { -0.069466f, -0.313855f, +0.023899f },  //  2 R_hip
        { -0.004328f, -0.114370f, +0.001523f },  //  3 spine1
        { +0.102001f, -0.689938f, +0.016908f },  //  4 L_knee
        { -0.107756f, -0.696424f, +0.015049f },  //  5 R_knee
        { +0.001159f, +0.020810f, +0.002615f },  //  6 spine2
        { +0.088406f, -1.087899f, -0.026785f },  //  7 L_ankle
        { -0.091982f, -1.094839f, -0.027263f },  //  8 R_ankle
        { +0.002616f, +0.073732f, +0.028040f },  //  9 spine3
        { +0.114764f, -1.143690f, +0.092503f },  // 10 L_foot
        { -0.117354f, -1.142983f, +0.096085f },  // 11 R_foot
        { -0.000162f, +0.287603f, -0.014817f },  // 12 neck
        { +0.081461f, +0.195482f, -0.006050f },  // 13 L_collar
        { -0.079143f, +0.192565f, -0.010575f },  // 14 R_collar
        { +0.004990f, +0.352572f, +0.036532f },  // 15 head
        { +0.172438f, +0.225951f, -0.014918f },  // 16 L_shoulder
        { -0.175155f, +0.225116f, -0.019718f },  // 17 R_shoulder
        { +0.432050f, +0.213179f, -0.042374f },  // 18 L_elbow
        { -0.428897f, +0.211787f, -0.041119f },  // 19 R_elbow
        { +0.681284f, +0.222165f, -0.043545f },  // 20 L_wrist
        { -0.684196f, +0.219560f, -0.046679f },  // 21 R_wrist
        { +0.765326f, +0.214003f, -0.058491f },  // 22 L_hand
        { -0.768817f, +0.213442f, -0.056994f },  // 23 R_hand
    };
}
