"""Generate a C++ header with SMPL rest data (positions, parents, bone names).

Reads smpl_rest.json (from tools/dump_smpl_rest.py) and emits SMPLRestData.h
as compile-time constants for the UE C++ AnimNode.

Usage:
    python tools/gen_smpl_rest_header.py \\
        --input  ../smpl_rest.json \\
        --output ../unreal/Source/MotionRetarget/Public/SMPLRestData.h
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from config.bone_mapping import SMPL_TO_UE_BONE


HEADER_TEMPLATE = """\
// AUTO-GENERATED by python/tools/gen_smpl_rest_header.py — do not edit by hand.
// Source: smpl_rest.json (SMPL neutral model, β=0 rest pose, Y-up meters).

#pragma once

#include "CoreMinimal.h"

namespace SMPLRest
{{
    /** Number of SMPL body joints. */
    constexpr int32 NumJoints = 24;

    /** Parent joint index (-1 = root/pelvis). */
    constexpr int32 Parents[NumJoints] = {{
{parents}
    }};

    /**
     * Primary chain child for each joint (used for bone direction). -1 = leaf.
     * Pelvis picks spine1 as primary (torso), not the hips (they're separate
     * chains). Wrist picks hand even though hand has no UE counterpart —
     * gives wrist a bone direction for swing retargeting.
     */
    constexpr int32 ChainChild[NumJoints] = {{
        3,   // 0  pelvis → spine1  (primary spine child)
        4,   // 1  L_hip → L_knee
        5,   // 2  R_hip → R_knee
        6,   // 3  spine1 → spine2
        7,   // 4  L_knee → L_ankle
        8,   // 5  R_knee → R_ankle
        9,   // 6  spine2 → spine3
        10,  // 7  L_ankle → L_foot
        11,  // 8  R_ankle → R_foot
        12,  // 9  spine3 → neck  (primary; L_collar/R_collar are separate chains)
        -1,  // 10 L_foot  (leaf)
        -1,  // 11 R_foot  (leaf)
        15,  // 12 neck → head
        16,  // 13 L_collar → L_shoulder
        17,  // 14 R_collar → R_shoulder
        -1,  // 15 head  (leaf)
        18,  // 16 L_shoulder → L_elbow
        19,  // 17 R_shoulder → R_elbow
        20,  // 18 L_elbow → L_wrist
        21,  // 19 R_elbow → R_wrist
        22,  // 20 L_wrist → L_hand
        23,  // 21 R_wrist → R_hand
        -1,  // 22 L_hand  (leaf, no UE counterpart)
        -1,  // 23 R_hand  (leaf, no UE counterpart)
    }};

    /** SMPL joint names (for logging / debugging). */
    static const TCHAR* const JointNames[NumJoints] = {{
{joint_names}
    }};

    /** UE mannequin bone name for each SMPL joint (empty = skip). */
    static const TCHAR* const UEBoneNames[NumJoints] = {{
{ue_bone_names}
    }};

    /**
     * SMPL joint world positions at rest (β=0, pose=0). SMPL Y-up meters.
     * pelvis is at approximately (0, -0.22, 0.03) — SMPL canonical has the
     * root offset from the origin by the mesh centroid; we keep that offset
     * for accurate FK.
     */
    constexpr float RestPositionsYupMeters[NumJoints][3] = {{
{positions}
    }};
}}
"""


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--input", "-i", required=True)
    p.add_argument("--output", "-o", required=True)
    args = p.parse_args()

    with open(args.input, "r", encoding="utf-8") as f:
        data = json.load(f)

    bones = data["bones"]
    if len(bones) != 24:
        print(f"[error] expected 24 bones, got {len(bones)}", file=sys.stderr)
        return 1

    parents_lines = []
    joint_names_lines = []
    ue_bone_names_lines = []
    positions_lines = []

    for i, entry in enumerate(bones):
        parents_lines.append(f"        {entry['parent_index']:d},  // {i:2d} {entry['name']}")

        joint_names_lines.append(
            f'        TEXT("{entry["name"]}"),  // {i:2d}'
        )

        ue_name = SMPL_TO_UE_BONE.get(i, "")
        ue_bone_names_lines.append(
            f'        TEXT("{ue_name}"),  // {i:2d} {entry["name"]}'
        )

        pos = entry["position_world"]
        positions_lines.append(
            f'        {{ {pos[0]:+.6f}f, {pos[1]:+.6f}f, {pos[2]:+.6f}f }},  '
            f'// {i:2d} {entry["name"]}'
        )

    header = HEADER_TEMPLATE.format(
        parents="\n".join(parents_lines),
        joint_names="\n".join(joint_names_lines),
        ue_bone_names="\n".join(ue_bone_names_lines),
        positions="\n".join(positions_lines),
    )

    out_path = Path(args.output).resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header, encoding="utf-8")
    print(f"[gen_smpl_rest_header] wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
